### PR TITLE
Prevent crashes from missing socket error handlers

### LINKED ISSUE #122: [Maybe Bug] Incompatibility with firebase functions emulator
Since installing safe-chain, I've been having a terrible experience (well, worse than usual) with local firebase emulators, specifically the functions emulators. Usually they will start up OK, but any changes in source code cause the emulators to reload (as they should) but then invariably throw an error. Examples include:
```
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

Node.js v20.11.0
```

and 

```
i  functions: Finished "us-central1-appXYZ" in 8370.6382ms
Safe-chain: error connecting to 169.254.169.254: - connect ETIMEDOUT 169.254.169.254:443
Safe-chain: error connecting to 169.254.169.254: - connect ETIMEDOUT 169.254.169.254:443
Safe-chain: error connecting to 169.254.169.254: - connect ETIMEDOUT 169.254.169.254:443
Safe-chain: error connecting to 169.254.169.254: - connect ETIMEDOUT 169.254.169.254:443
```

Anyone else had experience with this? I'm using firebase tools v14.20.0.

### PR DESCRIPTION
**Pull request by SanderDeclerck**
Fixes #122

### CODE REVIEW

File: packages/safe-chain/src/registryProxy/mitmRequestHandler.js [hunk 1]
```diff
@@ -37,13 +37,19 @@ function createHttpsServer(hostname, isAllowed) {
...
+  const server = https.createServer(
     {
       key: cert.privateKey,
       cert: cert.certificate,
     },
     handleRequest
   );
+
+  server.on("error", (err) => {
+    ui.writeError(`Safe-chain: HTTPS server error: ${err.message}`);
```
Comment (hansott) [inline packages/safe-chain/src/registryProxy/mitmRequestHandler.js:50]: Where does `ui` come from? Needs import?

File: packages/safe-chain/src/registryProxy/mitmRequestHandler.js [hunk 2]
```diff
@@ -37,13 +37,19 @@ function createHttpsServer(hostname, isAllowed) {
...
-  return https.createServer(
+  const server = https.createServer(
     {
       key: cert.privateKey,
       cert: cert.certificate,
     },
     handleRequest
   );
+
+  server.on("error", (err) => {
```
Comment (bitterpanda63) [inline packages/safe-chain/src/registryProxy/mitmRequestHandler.js:49]: we're not ending req or exiting here?

File: packages/safe-chain/src/registryProxy/mitmRequestHandler.js (hunk 1 above)
Comment (SanderDeclerck) [reply packages/safe-chain/src/registryProxy/mitmRequestHandler.js:50]: Idd, weird that oxlint isn't picking up this :/

File: packages/safe-chain/src/registryProxy/tunnelRequestHandler.js [hunk 3]
```diff
@@ -24,19 +24,21 @@ export function tunnelRequest(req, clientSocket, head) {
...
   const serverSocket = net.connect(port || 443, hostname, () => {
     clientSocket.write("HTTP/1.1 200 Connection Established\r\n\r\n");
     serverSocket.write(head);
     serverSocket.pipe(clientSocket);
     clientSocket.pipe(serverSocket);
   });
 
+  clientSocket.on("error", () => {
+    // This can happen if the client TCP socket sends RST instead of FIN.
+    // Not subscribing to 'close' event will cause node to throw and crash.
```
Comment (bitterpanda63) [inline packages/safe-chain/src/registryProxy/tunnelRequestHandler.js]: we are subscribing to error event right?

File: packages/safe-chain/src/registryProxy/tunnelRequestHandler.js [hunk 4]
```diff
@@ -100,9 +102,13 @@ function tunnelRequestViaProxy(req, clientSocket, head, proxyUrl) {
...
       );
-      if (clientSocket.writable) {
-        clientSocket.end("HTTP/1.1 502 Bad Gateway\r\n\r\n");
-      }
+    } else {
+      ui.writeError(
+        `Safe-chain: proxy socket error after connection - ${err.message}`
+      );
+    }
+    if (clientSocket.writable) {
```
Comment (bitterpanda63) [inline packages/safe-chain/src/registryProxy/tunnelRequestHandler.js]: this code will now also run even if connection was successful

File: packages/safe-chain/src/registryProxy/mitmRequestHandler.js (hunk 2 above)
Comment (SanderDeclerck) [reply packages/safe-chain/src/registryProxy/mitmRequestHandler.js:49]: We're not initiating the request here.

I updated the PR to write 502 and close the response if possible.

File: packages/safe-chain/src/registryProxy/tunnelRequestHandler.js (hunk 3 above)
Comment (SanderDeclerck) [reply packages/safe-chain/src/registryProxy/tunnelRequestHandler.js]: Yeah, was wrong in the comment.
