### PR TITLE
Escape special chars in shell scripts

### LINKED ISSUE #89: [Bug]: ampersand `&` character not escaped by single-tick in `cypress run`
### Bug Description

When safe-chain is active, the escaping of special characters for the shell by placing them between single quotes fails.

Escaping with backslash still works.

See details below.

### Steps to Reproduce

Please find below 1 failing example and 2 passing examples:

**FAILING EXAMPLE:**

**Given:**

Mac OS X 15.x
zsh

I had installed safe-chain globally:

```
npm install -g @aikidosec/safe-chain
```

this works as expected and added this line at bottom of .zshrc:

```
➜  ~ tail -3 .zshrc

source ~/.safe-chain/scripts/init-posix.sh # Safe-chain Zsh initialization script
```

**When:**

I then run 

```
 npx cypress run --env password='foo&bar'
```

**Then:**

the `bar` after the ampersand is not considered part of the `password` string, but is interpreted by `zsh` as "run this task in the background and try to run a `bar` command"

```
✔ Safe-chain: No malicious packages detected.
/bin/sh: bar: command not found
npm warn exec The following package was not found and will be installed: cypress@15.3.0
⠋
⠋
⠼
⠇
It looks like this is your first time using Cypress: 15.3.0

✔  Verified Cypress! /Users/peter_v/Library/Caches/Cypress/15.3.0/Cypress.app

Opening Cypress...

DevTools listening on ws://127.0.0.1:49814/devtools/browser/664...
Could not find a Cypress configuration file in this folder: ...
^C
```

**PASSING EXAMPLE:**

**Given:**

I commented out the activation of safe-chain in .zshrc and started a new terminal:

```
➜  ~ tail -3 .zshrc

# source ~/.safe-chain/scripts/init-posix.sh # Safe-chain Zsh initialization script
```

**When:**

In a newly opened terminal, I then run 

```
 npx cypress run --env password='foo&bar'
```

**Then:**

npx runs as expected and escapes the content between `'...'` correctly as a string.

``` 
➜  ~ npx cypress run --env password='foo&bar'

DevTools listening on ws://127.0.0.1:50271/devtools/browser/9eaf21...
Could not find a Cypress configuration file in this folder: ...
➜  ~
```

**SECOND PASSING EXAMPLE**

**Given:**

I re-activated safe-chain in .zshrc and started a new terminal:

➜  ~ tail -3 .zshrc

source ~/.safe-chain/scripts/init-posix.sh # Safe-chain Zsh initialization script

**When:**

Using `\` to escape the `&` in the password:

In a newly opened terminal, I then run 

```
➜  ~ npx cypress run --env password='foo\&bar'
```

**Then:**

npx runs as expected and escapes the `&` correctly:

```
✔ Safe-chain: No malicious packages detected.

DevTools listening on ws://127.0.0.1:50311/devtools/browser/ca42ac97...
Could not find a Cypress configuration file in this folder: ...
➜  ~
``` 

### Environment

- OS: Mac OS 15.x
- npm: 11.6.0
- Cypress: 15.3.0
```
- ➜  ~ npm -g list | grep safe
├── @aikidosec/safe-chain@1.0.24
```
```
➜  ~ nvm current
v20.19.4
```

### Error Logs

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by SanderDeclerck**
Fixes #89

### CODE REVIEW

File: packages/safe-chain/src/utils/safeSpawn.js [hunk 1]
```diff
@@ -1,9 +1,15 @@
...
-    return '"' + arg.replaceAll('"', '\\"') + '"';
+  // Shell metacharacters that need escaping
+  // These characters have special meaning in shells and need to be quoted
+  const shellMetaChars = /[ "&'|;<>()$`\\!*?[\]{}~#]/;
+
+  // If argument contains shell metacharacters, wrap in double quotes
+  // and escape characters that are special even inside double quotes
+  if (shellMetaChars.test(arg)) {
+    // Inside double quotes, we need to escape: " $ ` \
+    return '"' + arg.replace(/(["`$\\])/g, '\\$1') + '"';
```
Comment (bitterpanda63) [inline packages/safe-chain/src/utils/safeSpawn.js]: would make it separate so it's easier to read

File: packages/safe-chain/src/utils/safeSpawn.spec.js [hunk 2]
```diff
@@ -105,5 +105,14 @@ describe("safeSpawn", () => {
       assert.strictEqual(spawnCalls[0].command, "npm install axios --save");
       assert.strictEqual(spawnCalls[0].options.shell, true);
     });
+
+    it(`should escape ampersand character (${variant})`, async () => {
```
Comment (bitterpanda63) [inline packages/safe-chain/src/utils/safeSpawn.spec.js]: would add some extra unit tests for both regexes (ones where other chars are escaped because its inside double quote string)

File: packages/safe-chain/src/utils/safeSpawn.js [hunk 3]
```diff
@@ -1,22 +1,66 @@
...
-  const escapedArgs = args.map(escapeArg);
+  const escapedArgs = args.map(sanitizeShellArgument);
+
   return `${command} ${escapedArgs.join(" ")}`;
 }
 
+function resolveCommandPath(command) {
+  // command will be "npm", "yarn", etc.
+  // Use 'command -v' to find the full path
+  const fullPath = execSync(`command -v ${command}`, {
```
Comment (bitterpanda63) [inline packages/safe-chain/src/utils/safeSpawn.js:42]: should we do some eccaping for the command itself?

Comment (bitterpanda63) [reply packages/safe-chain/src/utils/safeSpawn.js:42]: mb just useful final check, also to get aikido scanner of the case
